/**
 * RRSP Loan Maximizer Calculator
 * Calculates optimal RRSP loan amount using Canadian tax brackets
 *
 * Tax data can be loaded from:
 * 1. Hardcoded histrocial data (2024)
 * 2. External JSON file generated by canatax Python script (current year)
 */

// ============================================
// Tax Data Configuration
// ============================================

// Default/current tax year
const CURRENT_TAX_YEAR = 2025;

// Historical tax data (kept as fallback)
const HISTORICAL_TAX_DATA = {
    2024: {
        federal: [
            { min: 0, max: 55867, rate: 0.15 },
            { min: 55867, max: 111733, rate: 0.205 },
            { min: 111733, max: 173205, rate: 0.26 },
            { min: 173205, max: 246752, rate: 0.29 },
            { min: 246752, max: Infinity, rate: 0.33 }
        ],
        provincial: {
            AB: {
                name: 'Alberta',
                brackets: [
                    { min: 0, max: 148269, rate: 0.10 },
                    { min: 148269, max: 177922, rate: 0.12 },
                    { min: 177922, max: 237230, rate: 0.13 },
                    { min: 237230, max: 355845, rate: 0.14 },
                    { min: 355845, max: Infinity, rate: 0.15 }
                ]
            },
            BC: {
                name: 'British Columbia',
                brackets: [
                    { min: 0, max: 47937, rate: 0.0506 },
                    { min: 47937, max: 95875, rate: 0.077 },
                    { min: 95875, max: 110076, rate: 0.105 },
                    { min: 110076, max: 133664, rate: 0.1229 },
                    { min: 133664, max: 181232, rate: 0.147 },
                    { min: 181232, max: 252752, rate: 0.168 },
                    { min: 252752, max: Infinity, rate: 0.205 }
                ]
            },
            ON: {
                name: 'Ontario',
                brackets: [
                    { min: 0, max: 51446, rate: 0.0505 },
                    { min: 51446, max: 102894, rate: 0.0915 },
                    { min: 102894, max: 150000, rate: 0.1116 },
                    { min: 150000, max: 220000, rate: 0.1216 },
                    { min: 220000, max: Infinity, rate: 0.1316 }
                ]
            }
        }
    }
};

// Active tax data (will be populated with historical + loaded data)
let TAX_DATA = {
    availableYears: [2024],
    federal: {
        2024: HISTORICAL_TAX_DATA[2024].federal
    },
    provincial: {
        2024: HISTORICAL_TAX_DATA[2024].provincial
    }
};

// Current selected year (default to current tax year)
let selectedYear = CURRENT_TAX_YEAR;

// ============================================
// Tax Data Loading (from canatax JSON)
// ============================================

/**
 * Load tax data from external JSON file (generated by canatax)
 * The file should be named 'tax_brackets_YYYY.json'
 */
async function LoadExternalTaxData(year) {
    try {
        const response = await fetch(`tax_brackets_${year}.json`);
        if (!response.ok) {
        console.log(`No external tax data found for ${year}, using fallback if available`);
            return false;
        }

        const data = await response.json();

        // Validate the data structure
        if (!data.federal || !data.provincial) {
            console.error(`Invalid tax data structure for ${year}`);
            return false;
        }

        // Convert "Infinity" strings back to Infinity
        const processedData = processInfinityValues(data);

        // Add to TAX_DATA
        TAX_DATA.federal[year] = processedData.federal;
        TAX_DATA.provincial[year] = processedData.provincial;

        if (!TAX_DATA.availableYears.includes(year)) {
            TAX_DATA.availableYears.push(year);
            TAX_DATA.availableYears.sort((a, b) => b - a);
        }

        console.log(`Loaded tax data for ${year} from external source`);
        return true;
    } catch (error) {
        console.log(`Could not load external tax data for ${year}:`, error.message);
        return false;
    }
}

/**
 * Convert "Infinity" strings in JSON to actual Infinity values
 */
function processInfinityValues(data) {
    const process = (brackets) => {
        return brackets.map(b => ({
            ...b,
            max: b.max === "Infinity" || b.max === null ? Infinity : b.max
        }));
    };

    return {
        federal: process(data.federal),
        provincial: Object.fromEntries(
            Object.entries(data.provincial).map(([key, value]) => [
                key,
                {
                    name: value.name,
                    brackets: process(value.brackets)
                }
            ])
        )
    };
}

/**
 * Initialize tax data - Load current year from external source
 */
async function initializeTaxData() {
    // Try to load current year data
    const loaded = await LoadExternalTaxData(CURRENT_TAX_YEAR);

    if (!loaded) {
        // If current year data not available, show warning
        console.warn(`Tax data for ${CURRENT_TAX_YEAR} not available. Please run the canatax script to generate it.`);
        // Default to most recent available year
        selectedYear = Math.max(...TAX_DATA.availableYears);
    }

    // Update UI
    populateYearSelector();
    updateTaxBracketDisplay();
}

// ============================================ 
// Tax Data Access Function
// ============================================

/**
 * Check if tax data is avilable for a specific year
 */
function isYearAvailable(year) {
    return TAX_DATA.availableYears.includes(year);
}

/**
 * Get federal tax brackets for the selected year
 */
function getFederalBrackets(year = selectedYear) {
    if (!isYearAvailable(year)) {
        return null;
    }
    return TAX_DATA.federal[year];
}

/**
 * Get provincial tax brackets for the selected year and province
 */
function getProvincialBrackets(provinceCode, year = selectedYear) {
    if (!isYearAvailable(year)) {
        return null;
    }
    return TAX_DATA.provincial[year] && TAX_DATA.provincial[year][provinceCode] ? TAX_DATA.provincial[year][provinceCode] : null;
}

/**
 * Get all available years
 */
function getAvailableYears() {
    return TAX_DATA.availableYears;
}

// ============================================
// Loan Interest Calculation Functions
// ============================================

/**
 * Calculate compound interest
 * @param {number} principal - Initial loan amount
 * @param {number} annualRate - Annual interest rate (as decimal, e.g., 0.065 for 6.5%)
 * @param {number} timeYears - Time in years
 * @param {string} compounding - 'daily', 'monthly', or 'annually'
 * @returns {object} - Interest calculation results
 */
function calculateCompoundInterest(principal, annualRate, timeYears, compounding) {
    // Compounding periods per year
    const periodsPerYear = {
        daily: 365,
        monthly: 12,
        annually: 1
    };

    const n = periodsPerYear[compounding] || 12;

    // Compound interest formula: A = P(1 + r/n)^(nt)
    const amount = principal * Math.pow((1 + annualRate / n), n * timeYears);
    const interestPaid = amount - principal;

    return {
        principal: principal,
        finalAmount: amount,
        interestPaid: interestPaid,
        effectiveRate: (amount / principal - 1) * 100 // Total percentage increase
    };
}

/**
 * Convert loan term to years
 * @param {number} term - The term value 
 * @param {string} unit - 'days', 'months', or 'years'
 * @returns {number} - Time in years
 */
function convertToYears(term, unit) {
    switch (unit) {
        case 'days': 
            return term / 365; 
        case 'months': 
            return term / 12; 
        case 'years': 
            return term; 
        default:
            return term; 
    }
}
/**
 * Format Loan term for display 
 */
function formatLoanTerm(term, unit) { 
    const unitNames = {
        days: term === 1 ? 'day' : 'days',
        months: term === 1 ? 'month' : 'months',
        years: term === 1 ? 'year' : 'years'
    };
    return `${term} ${unitNames[unit]}`;
}

/**
 * Format cæpounding frequency for display 
 */
function formatCompounding(compounding) {
    const names = {
        daily: 'Daily',
        monthly: 'Monthly',
        annually: 'Annually'
    };
    return names[compounding] || compounding;
}

// ============================================
// Tax Calculation Functions
// ============================================

/**
 * Get the marginal tax rate for a specific bracket system
 */
function getMarginalRate(income, brackets) {
    if (!Array.isArray(brackets) || brackets.length === 0) return 0;
    for (const bracket of brackets) {
        if ((income > bracket.min && income <= bracket.max) || (bracket.max === Infinity && income > bracket.min) || (income <= bracket.max && bracket.min === 0 && income >= 0)) {
            return bracket.rate;
        }
    }
    return brackets[0].rate;
}

/**
 * Get the bracket info for a specific income
 */
function getBracketInfo(income, brackets) { 
    for (let i = 0; i < brackets.length; i++) { 
        const bracket = brackets[i]; 
        if (income <= bracket.max || bracket.max === Infinity) { 
            return {
                index: i,
                bracket: bracket,
                rate: bracket.rate
            };
        }
    }
    return {
        index: brackets.length - 1,
        bracket: brackets[brackets.length - 1],
        rate: brackets[brackets.length - 1].rate
     };
}

/**
 * Calculate total tax for an income amount
 */
function calculateTax(income, brackets) {
    let tax = 0;
    let remainingIncome = income;

    for (const bracket of brackets) { 
        if (remainingIncome <= 0) break;
        
        const taxableInBracket = Math.min(
            remainingIncome,
            bracket.max - bracket.min
        );
        
        tax += taxableInBracket * bracket.rate;
        remainingIncome -= taxableInBracket;
    }

    return tax;
}

/**
 * Get combined marginal tax rate (federal + provincial)
 */
function getCombinedMarginalRate(income, province, year = selectedYear) {
    const federalBrackets = getFederalBrackets(year);
    const provincialData = getProvincialBrackets(province, year);

    if (!federalBrackets || !provincialData) {
        return null;
    }

    const federalRate = getMarginalRate(income, federalBrackets);
    const provincialRate = getMarginalRate(income, provincialData.brackets);

    return {
        federal: federalRate,
        provincial: provincialRate,
        combined: federalRate + provincialRate
    };
}

/** 
 * Calculate tax refund considering bracket changes 
 */
function calculateTaxRefund(income, contribution, province, year=selectedYear) {
    const federalBrackets = getFederalBrackets(year); 
    const provincialData = getProvincialBrackets(province, year); 
    
    if (!federalBrackets || !provincialData) { 
        return null; 
    }

    // calculate tax before RRSP contribution 
    const federalTaxBefore = calculateTax(income, federalBrackets); 
    const provincialTaxBefore = calculateTax(income, provincialData.brackets); 
    const totalTaxBefore = federalTaxBefore + provincialTaxBefore; 
    
    // Calculate tax after RRSP contribution
    const incomeAfter = Math.max(0, income - contribution); 
    const federalTaxAfter = calculateTax(incomeAfter, federalBrackets); 
    const provincialTaxAfter = calculateTax(incomeAfter, provincialData.brackets); 
    const totalTaxAfter = federalTaxAfter + provincialTaxAfter; 
    
    return { 
        taxBefore: totalTaxBefore, 
        taxAfter: totalTaxAfter, 
        refund: totalTaxBefore - totalTaxAfter, 
        effectiveRate: contribution > 0 ? (totalTaxBefore - totalTaxAfter) / contribution : 0
    };
}

/**
 * Calculate the optimal loan amount using iteration 
 */
function calculateOptimalLoan(income, currentContribution, contributionRoom, province, year = selectedYear) {
    // Get marginal rate at current income 
    const marginalRate = getCombinedMarginalRate(income, province, year); 

    if (!marginalRate) { 
        return null; 
    }
    
    let loanAmount = 0;
    let totalContribution = currentContribution; 
    let iterations = []; 
    
    // Iterative approach to handle bracket changes 
    let refund = calculateTaxRefund(income, currentContribution, province, year).refund;
    let iteration = 0;
    const maxIterations = 100;
    const threshold = 0.01; 

    let incrementalLoan = refund;
    
    while (incrementalLoan > threshold && iteration < maxIterations) { 
        if (totalContribution + incrementalLoan > contributionRoom) { 
            incrementalLoan = contributionRoom - totalContribution; 
            if (incrementalLoan <= 0) break; 
        } 

        loanAmount += incrementalLoan; 
        totalContribution += incrementalLoan; 

        const incrementalRefund = calculateTaxRefund(income, totalContribution, province, year).refund - 
                                  calculateTaxRefund(income, totalContribution - incrementalLoan, province, year).refund; 
        
        iterations.push({
            iteration: iteration + 1,
            loanAmount: loanAmount,
            totalContribution: totalContribution,
            incrementalRefund: incrementalRefund
        });

        incrementalLoan = incrementalRefund;
        iteration++;
    }

    const finalRefund = calculateTaxRefund(income, totalContribution, province, year).refund;
    
    const bracketBefore = getCombinedMarginalRate(income, province, year); 
    const incomeAfterRRSP = income - totalContribution; 
    const bracketAfter = getCombinedMarginalRate(incomeAfterRRSP, province, year); 
    
    return { 
        loanAmount: loanAmount, 
        totalContribution: totalContribution, 
        taxRefund: finalRefund, 
        outOfPocket: currentContribution + loanAmount - finalRefund, 
        marginalRateBefore: bracketBefore.combined, 
        marginalRateAfter: bracketAfter.combined, 
        bracketChanged: bracketAfter.combined !== bracketBefore.combined, 
        iterations: iterations, 
        iterationCount: iteration, 
        year: year 
    };
}

// ============================================
// UI Update Functions
// ============================================
/**
 * Format currency for display
 */
function formatCurrency(amount) { 
    return new Intl.NumberFormat('en-CA', {
        style: 'currency',
        currency: 'CAD',
        minimumFractionDigits: 2,
        maximumFractionDigits: 2
    }).format(amount);
}

/**
 * Format percentage for display
 */
function formatPercent(rate) { 
    return (rate * 100).toFixed(2) + '%'; 
}

/**
 * Populate the year selector with available years
 */
function populateYearSelector() { 
    const yearSelect = document.getElementById('tax-year'); 
    if (!yearSelect) return; 
    
    const years = getAvailableYears().sort((a, b) => b - a); // Sort descending 

    yearSelect.innerHTML = ''; 

  
    // Add available years 
    years.forEach(year => { 
        const option = document.createElement('option'); 
        option.value = year; 
        option.textContent = year; 
        if (year === selectedYear) { 
            option.selected = true; 
        }
        yearSelect.appendChild(option);
    });

    // Add upcoming years that aren't available yet (as disabled)
    const maxYear = Math.max(...years);
    for (let futureYear = maxYear + 1; futureYear <= CURRENT_TAX_YEAR + 1; futureYear++) {
        if (!years.includes(futureYear)) {
            const option = document.createElement('option');
            option.value = futureYear;
            option.textContent = `${futureYear} (Not Available)`;
            option.disabled = true;
            yearSelect.appendChild(option);
        }
    }

    // If selected year is not available, select the most recent available 
    if (!isYearAvailable(selectedYear)) { 
        selectedYear = Math.max(...years); 
        yearSelect.value = selectedYear; 
    }
}

/**
 * Handle year selection change
 */
function handleYearChange(e) { 
    const year = parseInt(e.target.value); 
    
    if (!isYearAvailable(year)) { 
        showYearUnavailableMessage(year); 
        e.target.value = selectedYear; 
        return; 
    } 

    selectedYear = year; 
    updateTaxBracketDisplay(selectedYear); 
    hideYearUnavailableMessage(); 

    // Update footer text 
    const footerYear = document.querySelector('.copyright'); 
    if (footerYear) { 
        footerYear.textContent = `Tax brackets based on ${year} Canadian federal and provincial rates: `; 
    }
}

/**
 * Show message when year is unavailable
 */
function showYearUnavailableMessage(year) { 
    let messageEl = document.getElementById('year-unavailable-message'); 

    if (!messageEl) { 
        messageEl = document.createElement('div'); 
        messageEl.id = 'year-unavailable-message'; 
        messageEl.className = 'year-unavailable-message'; 
        const yearSelect = document.getElementById('tax-year'); 
        yearSelect.parentNode.appendChild(messageEl); 
    }

    messageEl.textContent = `Tax bracket data for ${year} is not yet available. Please run the canatax script to generate it.`; 
    messageEl.style.display = 'block'; 
}

/**
 * Hide year unavailable message
 */
function hideYearUnavailableMessage() { 
    const messageEl = document.getElementById('year-unavailable-message');
    if (messageEl) {
        messageEl.style.display = 'none'; 
    }
}

/**
 * Update tax bracket display based on income, province, and year
 */
function updateTaxBracketDisplay() { 
    const province = document.getElementById('province').value; 
    const income = parseFloat(document.getElementById('annual-income').value) || 0; 

    const currentBracket = document.getElementById('current-bracket');
    const federalRate = document.getElementById('federal-rate');
    const provincialRate = document.getElementById('provincial-rate');

    if (!province || income <= 0) {
        currentBracket.textContent = '-';
        federalRate.textContent = '-';
        provincialRate.textContent = '-';
        return;
    }

    const rates = getCombinedMarginalRate(income, province, selectedYear);

    if (!rates) {
        currentBracket.textContent = 'N/A';
        federalRate.textContent = 'N/A';
        provincialRate.textContent = 'N/A';
        return;
    }

    currentBracket.textContent = formatPercent(rates.combined);
    federalRate.textContent = formatPercent(rates.federal);
    provincialRate.textContent = formatPercent(rates.provincial);
}

/**
 * Get loan interest inputs
 */
function getLoanInterestInputs() { 
    const interestRate = parseFloat(document.getElementById('interest-rate').value); 
    const loanTerm = parseFloat(document.getElementById('loan-term').value); 
    const loanTermUnit = document.getElementById('loan-term-unit').value; 
    const compounding = document.getElementById('compounding').value;

    // Check if interest calculation should be performed
    if (isNaN(interestRate) || interestRate <= 0 || isNaN(loanTerm) || loanTerm <= 0) {
        return null;
    }

    return {
        interestRate: interestRate / 100, // Convert from percentage to decimal
        loanTerm: loanTerm,
        loanTermUnit: loanTermUnit,
        compounding: compounding,
        timeYears: convertToYears(loanTerm, loanTermUnit)
    };
}

/**
 * Display calculation results
 */
function displayResults(results, inputs, interestResults = null) {
    const resultsSection = document.getElementById('results-section');
    if (resultsSection) resultsSection.classList.add('visible');

    const loanEl = document.getElementById('loan-amount');
    const totalContribEl = document.getElementById('total-contribution');
    const refundEl = document.getElementById('tax-refund');
    const outOfPocketEl = document.getElementById('out-of-pocket');

    if (loanEl) loanEl.textContent = formatCurrency(results.loanAmount);
    if (totalContribEl) totalContribEl.textContent = formatCurrency(results.totalContribution);
    if (refundEl) refundEl.textContent = formatCurrency(results.taxRefund);
    if (outOfPocketEl) outOfPocketEl.textContent = formatCurrency(results.outOfPocket);

    const breakdownContent = document.getElementById('breakdown-content');
    if (breakdownContent) {
        let html = `
            <div class="formula">
                Formula: Loan = (Contribution × Tax Rate) ÷ (1 - Tax Rate)<br>
                <small style="color: var(--color-text-dim);">Using ${results.year} tax brackets</small>
            </div>
            <div class="step">
                <span class="step-label">Your contribution:</span>
                <span class="step-value">${formatCurrency(inputs.currentContribution)}</span>
            </div>
            <div class="step">
                <span class="step-label">Marginal tax rate (${results.year}):</span>
                <span class="step-value">${formatPercent(results.marginalRateBefore)}</span>
            </div>
            <div class="step">
                <span class="step-label">Optimal loan amount:</span>
                <span class="step-value highlight">${formatCurrency(results.loanAmount)}</span>
            </div>
            <div class="step">
                <span class="step-label">Total RRSP contribution:</span>
                <span class="step-value">${formatCurrency(results.totalContribution)}</span>
            </div>
            <div class="step">
                <span class="step-label">Tax refund received:</span>
                <span class="step-value highlight">${formatCurrency(results.taxRefund)}</span>
            </div>
            <div class="step">
                <span class="step-label">Loan paid by refund:</span>
                <span class="step-value">${formatCurrency(Math.min(results.loanAmount, results.taxRefund))}</span>
            </div>
        `;

        if (results.loanAmount > results.taxRefund) {
            html += `
                <div class="step">
                    <span class="step-label">Remaining loan balance:</span>
                    <span class="step-value" style="color: var(--color-secondary);">${formatCurrency(results.loanAmount - results.taxRefund)}</span>
                </div>
            `;
        }

        breakdownContent.innerHTML = html;
    }

    const taxImpactContent = document.getElementById('tax-impact-content');
    if (taxImpactContent) {
        let taxImpactHTML = `
            <div class="tax-row">
                <span class="label">Taxable income before RRSP:</span>
                <span class="value">${formatCurrency(inputs.annualIncome)}</span>
            </div>
            <div class="tax-row">
                <span class="label">Total RRSP deduction:</span>
                <span class="value negative">-${formatCurrency(results.totalContribution)}</span>
            </div>
            <div class="tax-row">
                <span class="label">Taxable income after RRSP:</span>
                <span class="value">${formatCurrency(Math.max(0, inputs.annualIncome - results.totalContribution))}</span>
            </div>
        `;

        if (results.bracketChanged) {
            taxImpactHTML += `
                <div class="bracket-change">
                    <span class="arrow">📉</span>
                    <span>Tax bracket: </span>
                    <span class="from">${formatPercent(results.marginalRateBefore)}</span>
                    <span class="arrow">→</span>
                    <span class="to">${formatPercent(results.marginalRateAfter)}</span>
                </div>
            `;
        }

        taxImpactContent.innerHTML = taxImpactHTML;
    }

    const interestBreakdown = document.getElementById('interest-breakdown');
    if (interestBreakdown) {
        if (interestResults) {
            interestBreakdown.classList.remove('hidden');
            const rateEl = document.getElementById('result-interest-rate');
            const termEl = document.getElementById('result-loan-term');
            const compEl = document.getElementById('result-compounding');
            const paidEl = document.getElementById('result-interest-paid');
            const repayEl = document.getElementById('result-total-repayment');
            const netEl = document.getElementById('result-net-benefit');

            if (rateEl) rateEl.textContent = (interestResults.inputs.interestRate * 100).toFixed(2) + '%';
            if (termEl) termEl.textContent = formatLoanTerm(interestResults.inputs.loanTerm, interestResults.inputs.loanTermUnit);
            if (compEl) compEl.textContent = formatCompounding(interestResults.inputs.compounding);
            if (paidEl) paidEl.textContent = formatCurrency(interestResults.interestPaid);
            if (repayEl) repayEl.textContent = formatCurrency(interestResults.finalAmount);

            const netBenefit = results.taxRefund - (interestResults.interestPaid || 0);
            if (netEl) {
                netEl.textContent = formatCurrency(netBenefit);
                netEl.style.color = netBenefit >= 0 ? 'var(--color-success)' : 'var(--color-secondary)';
            }
        } else {
            interestBreakdown.classList.add('hidden');
        }
    }

    if (resultsSection) resultsSection.scrollIntoView({ behavior: 'smooth', block: 'start' });
}

/**
 * Handle form submission
 */
function handleSubmit(e) {
    e.preventDefault();

    const province = document.getElementById('province').value; 
    const annualIncome = parseFloat(document.getElementById('annual-income').value) || 0; 
    const contributionRoom = parseFloat(document.getElementById('contribution-room').value) || 0;
    const currentContribution = parseFloat(document.getElementById('current-contribution').value) || 0; 

    // Validation
    if (!province) {
        alert('Please select your province or territory.');
        return;
    }

    if (annualIncome <= 0) {
        alert('Please enter your annual income.');
        return;
    }

    if (contributionRoom <= 0) {
        alert('Please enter your available RRSP contribution room.');
        return;
    }

    if (currentContribution < 0) {
        alert('Please enter your current contribution amount.');
        return;
    }

    if (currentContribution > contributionRoom) {
        alert('Current contribution cannot exceed your available contribution room.');
        return;
    }

    if (!isYearAvailable(selectedYear)) {
        alert(`Tax data for ${selectedYear} is not available. Please select a different year or run the canatax script to generate it.`);
        return;
    }

    // Calculate results
    const results = calculateOptimalLoan(
        annualIncome,
        currentContribution,
        contributionRoom,
        province,
        selectedYear
    )

    if (!results) {
        alert('Unable to calculate results. Please check your inputs and try again.');
        return;
    }

    // Calculate interest if provided
    let interestResults = null;
    const interestInputs = getLoanInterestInputs();

    if (interestInputs) {
        const calculatedInterest = calculateCompoundInterest(
            results.loanAmount,
            interestInputs.interestRate,
            interestInputs.timeYears,
            interestInputs.compounding
        );

        interestResults = {
            ...calculatedInterest,
            inputs: interestInputs
        };
    }

    // Display results with animations
    displayResultsWithAnimation(results, {
        province,
        annualIncome,
        contributionRoom,
        currentContribution,
        year: selectedYear
    }, interestResults);
}

// ============================================
// Help Panel Functions
// ============================================

/**
 * Initialize the help panel functionality
 */
function initializeHelpPanel() {
    const helpFab = document.getElementById('help-fab'); 
    const helpPanel = document.getElementById('help-panel'); 
    const helpOverlay = document.getElementById('help-overlay'); 
    const helpPanelClose = document.getElementById('help-panel-close'); 
    const faqQuestions = document.querySelectorAll('.faq-question');
    
    if (!helpFab || !helpPanel) return;

    // Toggle help panel
    function openHelpPanel() {
        helpPanel.classList.add('open');
        helpPanel.setAttribute('aria-hidden', 'false');
        helpOverlay.classList.add('visible');
        helpFab.classList.add('active');
        document.body.style.overflow = 'hidden';
        
        // Focus the close button for accessibility
        setTimeout(() => helpPanelClose.focus(), 300);
    }

    function closeHelpPanel() {
        helpPanel.classList.remove('open');
        helpPanel.setAttribute('aria-hidden', 'true');
        helpOverlay.classList.remove('visible');
        helpFab.classList.remove('active');
        document.body.style.overflow = '';

        // Reutnr focus to the FAB
        helpFab.focus();
    }

    // Event listeners
    helpFab.addEventListener('click', () => {
        if (helpPanel.classList.contains('open')) {
            closeHelpPanel();
        } else {
            openHelpPanel();
        }
    });

    helpPanelClose.addEventListener('click', closeHelpPanel);
    helpOverlay.addEventListener('click', closeHelpPanel);

    // Close on Escape key
    document.addEventListener('keydown', (e) => {
        if (e.key === 'Escape' && helpPanel.classList.contains('open')) {
            closeHelpPanel();
        }
    });

    // FAQ Accordion functionality
    faqQuestions.forEach(question => {
        question.addEventListener('click', () => {
            const faqItem = question.closest('.faq-item');
            const isExpanded = question.getAttribute('aria-expanded') === 'true';

            // Close all other FAQ items
            faqQuestions.forEach(q => {
                q.setAttribute('aria-expanded', 'false');
                q.closest('.faq-item').classList.remove('expanded');
            });

            // Toggle current FAQ item
            if (!isExpanded) {
                question.setAttribute('aria-expanded', 'true');
                faqItem.classList.add('expanded');
            }
        });
    });

    // Focus trap for help panel
    helpPanel.addEventListener('keydown', (e) => {
        if (e.key !== 'Tab') return;

        const focusableElements = helpPanel.querySelectorAll(
            'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
        );
        if (!focusableElements.length) return;
        const firstElement = focusableElements[0];
        const lastElement = focusableElements[focusableElements.length - 1];

        if (e.shiftKey) {
            if (document.activeElement === firstElement) {
                e.preventDefault();
                lastElement.focus();
            }
        } else {
            if (document.activeElement === lastElement) {
                e.preventDefault();
                firstElement.focus();
            }
        }
    });
}

// ============================================
// Animation Utilities
// ============================================

/**
 * Animate a number counting up from 0 to the target value
 */
function animateCountUp(element, targetValue, duration = 5500) {
    // Check for reduced motion preference
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) {
        element.textContent = formatCurrency(targetValue);
        return;
    }

    const startTime = performance.now();
    const startValue = 0;

    function update(currentTime) {
        const elapsed = currentTime - startTime;
        const progress = Math.min(elapsed / duration, 1);
        
        // Easing function (ease-out-cubic)
        const easOut = 1 - Math.pow(1 - progress, 3);
        const currentValue = startValue + (targetValue - startValue) * easOut;

        element.textContent = formatCurrency(currentValue);

        if (progress < 1) {
            requestAnimationFrame(update);
        } else {
            element.textContent = formatCurrency(targetValue);
            element.classList.add('counting');
            setTimeout(() => element.classList.remove('counting'), 300);
        }
    }

    requestAnimationFrame(update);
}

/**
 * Enahanced display results with animations
 */
function displayResultsWithAnimation(results, inputs, interestResults = null) {
    const resultsSection = document.getElementById('results-section');
    resultsSection.classList.add('visible');

    // Animate main result values
    const loanAmountEl = document.getElementById('loan-amount');
    const totalContributionEl = document.getElementById('total-contribution');
    const taxRefundEl = document.getElementById('tax-refund' );
    const outOfPocketEl = document.getElementById('out-of-pocket');

   // Stagger the animations
    setTimeout(() => animateCountUp(loanAmountEl, results.loanAmount, 600), 100);
    setTimeout(() => animateCountUp(totalContributionEl, results.totalContribution, 600), 200);
    setTimeout(() => animateCountUp(taxRefundEl, results.taxRefund, 600), 300);
    setTimeout(() => animateCountUp(outOfPocketEl, results.outOfPocket, 600), 400);
    // Build breakdown content (same as before)
    const breakdownContent = document.getElementById('breakdown-content');
    breakdownContent.innerHTML = `
        <div class="formula">
            Formula: Loan = (Contribution Tax Rate) ÷ (1 - Tax Rate)<br>
            <small style="color: var( -- color-text-dim);">Using ${results.year} tax brackets</small>
        </div>
        <div class="step">
            <span class="step-label">Your contribution</span>
            <span class="step-value">${formatCurrency(inputs.currentContribution)}</span>
        </div>
        <div class="step">
            <span class="step-label">Marginal tax rate (${results.year})</span>
            <span class="step-value">${formatPercent(results.marginalRateBefore)}</span>
        </div>
        <div class="step">
            <span class="step-label">Optimal loan amount</span>
            <span class="step-value highlight">${formatCurrency(results.loanAmount)}</span>
        </div>
        <div class="step">
            <span class="step-label">Total RRSP contribution</span>
            <span class="step-value">${formatCurrency(results.totalContribution)}</span>
        </div>
        <div class="step">
            <span class="step-label">Tax refund received</span>
            <span class="step-value highlight">${formatCurrency(results.taxRefund)}</span>
        </div>
        <div class="step">
            <span class="step-label">Loan paid by refund</span>
            <span class="step-value">${formatCurrency(Math.min(results.loanAmount, results.taxRefund))}</span>
        </div>
        ${results.loanAmount > results.taxRefund ? `
        <div class="step">
            <span class="step-label">Remaining loan balance</span>
            <span class="step-value" style="color: var(--color-secondary);">${formatCurrency(results.loanAmount - results.taxRefund)}</span>
        </div>
        ` : ''}
    `;

    // Build tax impact content
    const taxImpactContent = document.getElementById('tax-impact-content');
    let taxImpactHTML = `
        <div class="tax-row">
            <span class="label">Taxable income before RRSP:</span>
            <span class="value">${formatCurrency(inputs.annualIncome)}</span>
        </div>
        <div class="tax-row">
            <span class="label">Total RRSP deduction:</span>
            <span class="value negative">-${formatCurrency(results.totalContribution)}</span>
        </div>
        <div class="tax-row">
            <span class="label">Taxable income after RRSP:</span>
            <span class="value">${formatCurrency(Math.max(0, inputs.annualIncome - results.totalContribution))}</span>
        </div>
    `;

    if (results.bracketChanged) {
        taxImpactHTML += `
            <div class="bracket-change">
                <span class="arrow">📉</span>
                <span>Tax bracket:</span>
                <span class="from">${formatPercent(results.marginalRateBefore)}</span>
                <span class="arrow">→</span>
                <span class="to">${formatPercent(results.marginalRateAfter)}</span>
            </div>
        `;
    }

    taxImpactContent.innerHTML = taxImpactHTML;

    // Handle interest breakdown
    const interestBreakdown = document.getElementById( 'interest-breakdown' );
    if (interestResults) {
        interestBreakdown.classList.remove('hidden');

        document.getElementById('result-interest-rate').textContent = (interestResults.inputs.interestRate * 100).toFixed(2) + '%';
        document.getElementById('result-loan-term').textContent = formatLoanTerm(interestResults.inputs.loanTerm, interestResults.inputs.loanTermUnit);
        document.getElementById('result-compounding').textContent = formatCompounding(interestResults.inputs.compounding);
        document.getElementById('result-interest-paid').textContent = formatCurrency(interestResults.interestPaid);
        document.getElementById('result-total-repayment').textContent = formatCurrency(interestResults.finalAmount);

        const netBenefit = results.taxRefund - interestResults.interestPaid;
        const netBenefitEl = document.getElementById('result-net-benefit');
        netBenefitEl.textContent = formatCurrency(netBenefit);
        netBenefitEl.style.color = netBenefit >= 0 ? 'var(--color-success)' : 'var(--color-secondary)';
    } else {
        interestBreakdown.classList.add('hidden');
    }

    // Scroll to results
    resultsSection.scrollIntoView({ behavior: 'smooth', block: 'start' });
}

// ============================================
// Event Listeners
// ============================================

document.addEventListener('DOMContentLoaded', async () => {
    // Initialize tax data (Load external data if available)
    await initializeTaxData();

    // Initialize help panel
    initializeHelpPanel();

    // Form submission
    const form = document.getElementById('calculator-form');
    form.addEventListener('submit', handleSubmit);

    // Year selector change
    const yearSelect = document.getElementById('tax-year');
    if (yearSelect) {
        yearSelect.addEventListener('change' , handleYearChange);
    }

    // Update tax bracket display on input changes
    const provinceSelect = document.getElementById('province');
    const incomeInput = document.getElementById('annual-income');

    provinceSelect.addEventListener('change', updateTaxBracketDisplay);
    incomeInput.addEventListener('input', updateTaxBracketDisplay);

    // Smooth scroll for hero CTA
    const heroCta = document.querySelector(' .hero-cta');
    if (heroCta) {
        heroCta.addEventListener('click', (e) => {
            e.preventDefault();
            const target = document.querySelector(heroCta.getAttribute('href'));
            if (target) {
                target.scrollIntoView({ behavior: 'smooth', block: 'start' });
            }
        });
    }
});

// Export functions for testing
if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        calculateOptimalLoan,
        getCombinedMarginalRate,
        calculateTaxRefund,
        calculateCompoundInterest,
        convertToYears,
        isYearAvailable,
        getAvailableYears,
        TAX_DATA,
        HISTORICAL_TAX_DATA
    };
}